[project]
name = "rtorrent-cleanup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bcoding>=1.5",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
